name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vim_version:
        - 'v8.2.1000'
        - 'v8.2.0000'
        - 'v8.1.0000'
        - 'v8.0.0000'
        download:
          - 'never'

    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Setup Vim
      uses: thinca/action-setup-vim@v1
      with:
        vim_version: ${{ matrix.vim_version }}

    - name: Install Dependencies
      run: | 
        git clone https://github.com/junegunn/vader.vim.git
        git clone https://github.com/vim-airline/vim-airline
        find $PWD/autoload/airline/themes -name "*.vim" > themes.txt

    - name: Run Test
      run: |
        vim --version
        vim --not-a-term -Nu <(cat << VIMRC
        filetype off
        set rtp+=vader.vim
        set rtp+=vim-airline
        set rtp+=.
        set rtp+=after
        filetype plugin indent on
        syntax enable
        VIMRC) -c 'Vader! test/*' > /dev/null
